let secretMessage = ['Learning', 'is', 'not', 'about', 'what', 'you', 'get', 'easily', 'the', 'first', 'time,', 'it', 'is', 'about', 'what', 'you', 'can', 'figure', 'out.', '-2015,', 'Chris', 'Pine,', 'Learn', 'JavaScript'];
secretMessage.pop();
console.log(secretMessage.length);
secretMessage.push('to', 'Program');
console.log(secretMessage.length);
secretMessage[7]='rigth';
console.log(secretMessage);
secretMessage.unshift();
console.log(secretMessage.length);
secretMessage.shift();
console.log(secretMessage.length);
secretMessage.splice(5, 5, 'know');
console.log(secretMessage.join());